#!/usr/bin/env python3
"""Test guardrails implementation."""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))

from src.llm import LLMService, guardrails
from src.utils import logger


def test_advisory_detection():
    """Test advisory question detection."""
    print("="*80)
    print("TEST 1: Advisory Question Detection")
    print("="*80)
    
    advisory_queries = [
        "Should I buy this stock?",
        "Do you recommend investing in Eternal?",
        "Is it good to buy Eternal?",
        "Can you advise me on this stock?",
        "What should I do with Eternal?",
    ]
    
    for query in advisory_queries:
        is_advisory = guardrails.is_advisory_question(query)
        print(f"Query: '{query}'")
        print(f"  Detected as advisory: {is_advisory}")
        if is_advisory:
            response = guardrails.handle_advisory_refusal(query, {})
            print(f"  Response: {response[:100]}...")
        print()


def test_predictive_detection():
    """Test predictive question detection."""
    print("="*80)
    print("TEST 2: Predictive Question Detection")
    print("="*80)
    
    predictive_queries = [
        "What is the target price for next month?",
        "Where will the stock price be next year?",
        "What will happen to Eternal's stock?",
        "Can you predict the future price?",
    ]
    
    for query in predictive_queries:
        is_predictive = guardrails.is_predictive_question(query)
        print(f"Query: '{query}'")
        print(f"  Detected as predictive: {is_predictive}")
        if is_predictive:
            response = guardrails.handle_predictive_refusal(query)
            print(f"  Response: {response[:100]}...")
        print()


def test_greeting_detection():
    """Test greeting detection."""
    print("="*80)
    print("TEST 3: Greeting Detection")
    print("="*80)
    
    greetings = [
        "Hello",
        "Hi there",
        "Hey",
        "Thanks",
        "Thank you",
        "Bye",
    ]
    
    for greeting in greetings:
        is_greeting = guardrails.is_greeting(greeting)
        print(f"Query: '{greeting}'")
        print(f"  Detected as greeting: {is_greeting}")
        if is_greeting:
            response = guardrails.handle_greeting(greeting)
            print(f"  Response: {response}")
        print()


def test_neutral_tone():
    """Test neutral tone enforcement."""
    print("="*80)
    print("TEST 4: Neutral Tone Enforcement")
    print("="*80)
    
    emotional_text = "This is a multibagger stock that is skyrocketing! It's cheap and a safe investment."
    neutral_text = guardrails.filter_emotional_words(emotional_text)
    
    print(f"Original: {emotional_text}")
    print(f"Filtered: {neutral_text}")
    print()


def test_disclaimer():
    """Test disclaimer injection."""
    print("="*80)
    print("TEST 5: Disclaimer Injection")
    print("="*80)
    
    text = "This company shows strong growth potential."
    with_disclaimer = guardrails.add_disclaimer(text, "bull_bear")
    
    print(f"Original: {text}")
    print(f"With Disclaimer: {with_disclaimer}")
    print()


def test_full_flow():
    """Test full flow with LLM service."""
    print("="*80)
    print("TEST 6: Full Flow with Guardrails")
    print("="*80)
    
    service = LLMService()
    
    # Test advisory question
    print("\n1. Testing advisory question:")
    result = service.answer_query("ETERNAL", "Should I buy this stock?")
    print(f"   Query: 'Should I buy this stock?'")
    print(f"   Response: {result.get('answer', '')[:150]}...")
    print(f"   Type: {result.get('type', 'N/A')}")
    
    # Test predictive question
    print("\n2. Testing predictive question:")
    result = service.answer_query("ETERNAL", "What will be the stock price next month?")
    print(f"   Query: 'What will be the stock price next month?'")
    print(f"   Response: {result.get('answer', '')[:150]}...")
    print(f"   Type: {result.get('type', 'N/A')}")
    
    # Test greeting
    print("\n3. Testing greeting:")
    result = service.answer_query("ETERNAL", "Hello")
    print(f"   Query: 'Hello'")
    print(f"   Response: {result.get('answer', '')}")
    print(f"   Type: {result.get('type', 'N/A')}")
    
    # Test normal query
    print("\n4. Testing normal query:")
    result = service.answer_query("ETERNAL", "What is the P/E ratio?")
    print(f"   Query: 'What is the P/E ratio?'")
    print(f"   Response: {result.get('answer', '')[:150]}...")
    print(f"   Type: {result.get('type', 'N/A')}")
    
    # Test bull/bear with disclaimer
    print("\n5. Testing bull/bear case (should have disclaimer):")
    result = service.get_bull_bear_case("ETERNAL")
    response = result.get('full_response', '')
    has_disclaimer = "*Generated by AI" in response or "*Not a buy/sell recommendation" in response
    print(f"   Has disclaimer: {has_disclaimer}")
    print(f"   Response snippet: {response[-200:]}")


def main():
    """Run all guardrail tests."""
    print("\n" + "🛡️" * 40)
    print("GUARDRAILS TESTING")
    print("🛡️" * 40)
    
    test_advisory_detection()
    test_predictive_detection()
    test_greeting_detection()
    test_neutral_tone()
    test_disclaimer()
    test_full_flow()
    
    print("\n" + "="*80)
    print("✅ Guardrails Testing Complete")
    print("="*80)


if __name__ == "__main__":
    main()


